module.exports = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'category',
      label: 'Web',
      items: [
        {
          type: 'link',
          label: 'Client JS',
          href: 'https://arkemishub.github.io/clientjs',
        },
        {
          type: 'link',
          label: 'UI Components',
          href: 'ui',
        },
        {
          type: 'link',
          label: 'Form',
          href: 'form',
        },
        {
          type: 'link',
          label: 'Table',
          href: 'table',
        },
      ],
    },
  ],
};
